[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****
In this part of the documentation the development team will describe all the main requirements and general information required to start designing the project's architecture.

That information will be subdivided in the following sections
*Requirements Overview, which describes the functionality of the project.
*Quality Goals, which contains information regarding the level of quality the team aims to achieve.
*Stakeholders, a sum of the main groups of people interested on the project, and also other groups that need to know the details of this specific architecture.


=== Requirements Overview

[role="arc42help"]
****
The LoMap system is a software solution that allows the citizens of a city to share places of interest as well as allow businesses to share their locations to potential clients. These places are part of a map, and the users can give feedback about them to other users.

The LoMap system must accomplish the following requirements:

* Users must be able to add locations of different categories, including bars, restaurants, shops, sights and monuments.
*	Users must be able to show the locations in a map window.
*	Users must be able to add review scores, comments and pictures about added places.
*	Users must be able to manage the information that is accessible with other users, which can be part of their friends or a group of friends.
*	The information about the places of each user should not be fully centralized.
*	The privacy of each user should be respected as much as possible without interfering with other aspects of the application such as the performance.
*	Users must be able to see places of their friends.
*	Users must be able to filter the places they see in the map by friends or category.
****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

.Quality goals ordered by priority (from most to least important)
[options="header",cols="1,3"]
|===
|Quality Goal|Description
| Usability | Non technical users must be able to use the app easily. Aesthetics must be familiar and understandable to them.
| Privacy | Users can control the data that is shared with the app thanks to SOLID principles and the use of pods.
| Efficiency | There must be a medium point between privacy and efficiency (all the information may not be stored inside the pods due to decreases in performance.
| Testability | The application should be able to go through different test and complete them successfully.



|===

=== Stakeholders

[role="arc42help"]

****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| Deployment city/ Client | Brussels City Hall | Have a functional application that adds value to the community, obtaining a benefit for local businesses and tourism.
| Responsible company | HappySw | Development of a generic project expandable to other cities.
| Main beneficiaries | Public users | Have an easily accessible and useful consultation and discovery service for premises or businesses.
| Side beneficiaries | Businesses benefited | Obtain greater visibility and approach to the public, especially to the tourists of the city.
| Project managers | Subject teachers | Development by the students of a functional application that meets the established criteria and can serve as a prototype for a real service.
| Developers | Lomap_es4a team | Carrying out a serious project with a view to the future in which to develop your potential and show your technical skills.

|===
