[[section-solution-strategy]]
== Solution Strategy

=== Technology decisions
.TypeScript:
We decided to use this programming language because it's one of the most suitable to develop web apps. Like JavaScript, it provides all the capabilities that a language used for the web and it helps the developers by being statically typed. Our team has experience with Java, so a statically typed language is easier to use and understand for us.

.Docker containers:
The docker containers can be used during development as they provide a uniform enviroment to run the application.

.WebStorm or Visual Studio Colde:
We will use either WebStorm or Visual Studio Colde develop our project, each member of the development team can choose to work with either one of them.

.Github Desktop:
Some members of the team will use Github IDEs such as Github Destopk, Github Kraken or native Github

=== How are the quality goals going to be reached?
.Usability:
Our interfaces will be intuitive and easy to use for anyone.

.Privacy:
The essential information will be stored in SOLID PODs providing a strong privacy.

.Eficiency:
The performance will be smooth, by using the SOLID PODs correctly.

.Testability:
The team will test the app manually and automatically 

***
