[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== Login


[plantuml,"Sequence diagram",png]
----
actor User
entity App
database Pod as "DB"
User--> App: Login data introduced
User --> App: Authentication Request
App --> Pod: Information Request
Pod -->App: Information Response
App --> User: Authentication Response
App --> User: Load of Information
App --> User: Confirmation of login
User --> App: Access to personal files adn use of the app
----
=== Map view
[plantuml,"Sequence diagram",png]
----
actor User
entity App
database Pod as "DB"
User --> App: Request to see the map
App --> Pod: Request user map data
Pod --> App: Load of the map
Pod --> App: Load of personal markers and points
App --> User: View of the map
----
=== New point/Map saved
[plantuml,"Sequence diagram",png]
----
actor User
entity App
database Pod as "DB"
User --> App: Request to create new marker
App --> User: Creation marker view
User --> App: Marker data
App -->App:Local data save
User -->App: Save request
App--> Pod: Remote save request
Pod --> App: DB Response
App --> User: Response feedback
----

===

