[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== Login


[plantuml,"Sequence diagram1",png]
----
actor User
entity App
entity PodProvider
User -> App: Choose provider
App ->PodProvider: Redirects to the provider
User -> PodProvider: Fills the fields to login
PodProvider --> App: Returns user information and creates session
App--> User: Gives personal view
----
=== Map view
[plantuml,"Sequence diagram2",png]
----
actor User
entity App
entity MapsApi
database Pod 
User -> App: Login
App -> MapsApi: Request user map data
Pod --> MapsApi: Load of markers
App -> MapsApi: Load of personal markers
MapsApi--> App : Markers loaded
App --> User: View of the map
----
=== New point/Map saved
[plantuml,"Sequence diagram3",png]
----

actor User
entity App
entity MapsApi
database Pod 

User -> App: Click the screen
App -> MapsApi: Request point data
App -> Pod: Save the point to the pod
MapsApi --> App: Returns marker 
App --> User: Creation marker view
----


