[[section-technical-risks]]
== Risks and Technical Debts

=== Risks

==== Organizational Risks

* GitHub is a very powerful tool when used correctly. As the developers tasked with developing the LoMap system do not have a lot of experience using GitHub in a professional work environment, it could become an issue. If not used correctly, Git and GitHub could become a liability and could delay development.
* If the number of meetings is insufficient the team may have difficulties understanding what their responsibilities are and it could pose coordination problems.
* If the number of meetings greater that the necesary amount, the team may lose time they could spend developing the system.

==== Technological Risks

* If the team does not properly understand the technologies used, the system may not satisfy the quality goals.

==== Technical Debt

* There is no REST API, which means there is no back-end. This is something that may hinder future development. Not having a REST API also means that the application will not be able to be used through requests to the REST API.
* There is no database, this means that there is no possibility to store useful information centrally. This might be useful for future growth of the application.
* The code could be better organized, currently a change may require to update various files. In the future the application may need to be refactored to lower its coupling.
