name: CI for LOMAP ES4A
on:
  release:
    types: [published]
    
  pull_request:
    branches:
      - master
      - develop
  
  push:
    branches:
      - master
      - develop

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm --prefix webapp ci
    - run: npm --prefix webapp test --coverage --watchAll
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@v1.8
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  e2e-tests:
    needs: [unit-tests]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm --prefix webapp install
    - run: npm --prefix webapp run build
    - run: npm --prefix webapp run test:e2e  
  deploy:
      needs: [e2e-tests]
      name: gh-pages deploy
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm --prefix webapp install
      - run: PUBLIC_URL=https://gonzalo-rr.github.io/lomap_es4a/ npm --prefix webapp run build
      - name: Deploy
        uses: cpina/github-action-push-to-another-repository@create-branch-if-needed-arg
        env:
            REACT_APP_GOOGLE_KEY: ${{ secrets.REACT_APP_GOOGLE_KEY }}
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
            source-directory: 'webapp/build'
            destination-github-username: 'gonzalo-rr'
            destination-repository-name: 'lomap_es4a'
            user-email: srgonzalorr@gmail.com
            commit-message: See ORIGIN_COMMIT from $GITHUB_REF
            target-branch: gh-pages
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY

