name: CI for LOMAP ES4A

on:
  release:
    types: [published]
    
  pull_request:
    branches:
      - master
      - develop
  
  push:
    branches:
      - master
      - develop
      
jobs:
  deploy:
     name: Deploy
     runs-on: ubuntu-latest
#     needs: [docker-push-webapp]
     steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: Send
       uses: dmnemec/copy_file_to_another_repo_action@main
       env:
         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
       with:
         source_file: 'ghcr.io/arquisoft/lomap_es4a/webapp:latest'
         user_name: 'gonzalo-rr'
         destination_repo: 'gonzalo-rr/lomap_es4a'
         destination_branch: 'gh-pages'

 
 
  # deploy:
  #   name: Deploy over SSH
  #   runs-on: ubuntu-latest
  #   needs: [docker-push-webapp]
  #   steps:
  #   - name: Deploy over SSH
  #     uses: fifsky/ssh-action@master
  #     with:
  #       host: ${{ secrets.DEPLOY_HOST }}
  #       user: ${{ secrets.DEPLOY_USER }}
  #       key: ${{ secrets.DEPLOY_KEY }}
  #       command: |
  #         wget https://raw.githubusercontent.com/arquisoft/lomap_es4a/master/docker-compose-deploy.yml -O docker-compose.yml
  #         docker-compose stop
  #         docker-compose rm -f
  #         docker-compose pull   
  #         docker-compose up -d
